--DETALLE DE  UN PEDIDO ESPECIFICO
SELECT det.CANTIDAD, det.DESCRIPCION, prod.NOMBRE
FROM PEDIDOS_TAB ped, PRODUCTO_TAB prod, DETALLEPED_TAB det, CLIENTE_TAB cli
WHERE ped.IDPEDIDO=det.IDPEDIDO
AND prod.IDPRODUCTO=det.IDPRODUCTO
AND cli.IDCLIENTE=det.IDCLIENTE
AND ped.IDPEDIDO=1
--PEDIDOS ENTREGADOS
SELECT DISTINCT ped.IDPEDIDO, cli.NOMBRECLI, ped.ESTATUS 
FROM PEDIDOS_TAB ped, PRODUCTO_TAB prod, DETALLEPED_TAB det, CLIENTE_TAB cli
WHERE ped.IDPEDIDO=det.IDPEDIDO
AND prod.IDPRODUCTO=det.IDPRODUCTO
AND cli.IDCLIENTE=det.IDCLIENTE
AND ped.ESTATUS='ENTREGADO'
--PEDIDOS PENDIENTES
SELECT DISTINCT ped.IDPEDIDO, cli.NOMBRECLI, ped.ESTATUS 
FROM PEDIDOS_TAB ped, PRODUCTO_TAB prod, DETALLEPED_TAB det, CLIENTE_TAB cli
WHERE ped.IDPEDIDO=det.IDPEDIDO
AND prod.IDPRODUCTO=det.IDPRODUCTO
AND cli.IDCLIENTE=det.IDCLIENTE
AND ped.ESTATUS='PENDIENTE'
--CANCELADOS
SELECT DISTINCT ped.IDPEDIDO, cli.NOMBRECLI, ped.ESTATUS 
FROM PEDIDOS_TAB ped, PRODUCTO_TAB prod, DETALLEPED_TAB det, CLIENTE_TAB cli
WHERE ped.IDPEDIDO=det.IDPEDIDO
AND prod.IDPRODUCTO=det.IDPRODUCTO
AND cli.IDCLIENTE=det.IDCLIENTE
AND ped.ESTATUS='CANCELADO'
--TODOS 
SELECT DISTINCT ped.IDPEDIDO, cli.NOMBRECLI, ped.ESTATUS 
FROM PEDIDOS_TAB ped, PRODUCTO_TAB prod, DETALLEPED_TAB det, CLIENTE_TAB cli
WHERE ped.IDPEDIDO=det.IDPEDIDO
AND prod.IDPRODUCTO=det.IDPRODUCTO
AND cli.IDCLIENTE=det.IDCLIENTE
